services:
  # Фронтенд - веб-приложение
  - type: web
    name: games-catalog-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://gc-backend-u67y.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    pullRequestPreviewsEnabled: true
  
  # Бэкенд - веб-сервис
  - type: web
    name: games-catalog-backend
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production 