services:
  - type: web
    name: games-catalog-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false # Установите URL вашего API на Render
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Директория fallback для всех маршрутов    
    pullRequestPreviewsEnabled: true 